### PR TITLE
Add corner case where the description from a data type profile used in a derived profile isn't used

### PR DESCRIPTION
**Pull request by pieter-edelman-nictiz**

### CODE REVIEW

**Comment by grahamegrieve** [comment]
Where does this sit with regard to https://chat.fhir.org/#narrow/channel/215610-shorthand/topic/IG.20publisher.20overwriting.20element.20description ?

**Comment by pieter-edelman-nictiz** [comment]
It's a bit different (and admittedly, a bit involved).
- First, there's a 'zib' layer with a profile that uses a data type profile. My expectation here would be that the profile renders the description from the data type profile (which is indeed the case).
- Then there's an 'nl-core' layer, where the original profile is derived. In this derived profile, the original use of the data type profile is overwritten by the use of another data type profile, with another description. My expectation is that the derived profile renders the description from the overwriting data type profile instead of the original data type profile. This is currently not the case for the Validator.

**Comment by grahamegrieve** [comment]
So I expected that after I merged this, the test would fail until I fixed the actual snapshot code, but no?

**Comment by grahamegrieve** [comment]
well, where's the specific bit in the expected outcome that you changed?

**Comment by pieter-edelman-nictiz** [comment]
In two places, see these screenshots. On the left is the output as produced by the Validator, on the right is the output in this PR.

nl-core-diff2

nl-core-diff1

**Comment by pieter-edelman-nictiz** [comment]
Note: conversion was done using `-version 4.0.1`

**Comment by grahamegrieve** [comment]
can you look at this:  https://github.com/FHIR/fhir-test-cases/pull/203

which of these changes are pertinent to the test case?

**Comment by pieter-edelman-nictiz** [comment]
I added pull request comments

**Pull request merged**
