### PR TITLE
add optional elements for capstmt.json

### PR DESCRIPTION
**Pull request by bdc-ehealth**

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
I'm not following this... why these changes?

**Comment by bdc-ehealth** [comment]
I'll check again, but as I set out to make the changes, the tests would also fail if the actual resource contains too much information, i.e. information allowed to be there, but not anticipated by the expected result. So I need to accommodate the expected results for any superfluous information in the actual resource (here the capacity statement) as well...

**Comment by grahamegrieve** [comment]
the capability statement matching is pattern based, unlike the other tests. So what is in there is the minimum required. There's no need for $optional$ - just leave the optional stuff out. That will leave the actual changes for us to discuss

**Comment by bdc-ehealth** [comment]
@grahamegrieve OK, the behaviour has changed... Nice improvement! You can ignore this pull request.

**Pull request closed without merging**
