### PR TITLE
2024 04 gg lookup

### PR DESCRIPTION
**Pull request by grahamegrieve**

### CODE REVIEW

**Comment by jimsteel** [comment]
Could we get some messages on the lookup test cases? Hard to know what's going wrong at present.

**Comment by grahamegrieve** [comment]
You should get both a message about he failure and a saved version after sorting so you can do diff

**Comment by jimsteel** [comment]
I'm seeing results like this in the test-results.json file (the first one is an "accepted" fail), with no status or message

```
{
          "name" : "simple-expand-isa-o2c2",
          "status" : "fail",
          "message" : "string property values differ at .expansion.contains[0].code\nExpected:\"code2aI\" for simple-expand-isa-o2c2\nActual  :\"code2a\""
        },
        {
          "name" : "simple-expand-prop",
          "status" : "pass"
        },
        {
          "name" : "simple-expand-regex",
          "status" : "pass"
        },
        {
          "name" : "simple-expand-regex2",
          "status" : "pass"
        },
        {
          "name" : "simple-lookup-1"
        },
        {
          "name" : "simple-lookup-2"
        }
```

**Comment by grahamegrieve** [comment]
This is the message: string property values differ at .expansion.contains[0].code\nExpected:\"code2aI\" for simple-expand-isa-o2c2\nActual  :\"code2a\

**Comment by jimsteel** [comment]
Yes, that one has a message. The lookup ones don't.

**Comment by grahamegrieve** [comment]
I'm guessing you need a new release of the validator to run them correctly

**Comment by jimsteel** [comment]
The validator I'm using comes from

curl -L -O https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar

So I'm pretty sure its the latest one.

**Comment by grahamegrieve** [comment]
Code for $lookup is not released yet

Grahame

——
FHIR Product Director at HL7; Adjunct Science Fellow, CSIRO
http://www.healthintersections.com.au / ***@***.*** /
+61 411 867 065
Benson & Grieve:   Principles of Health Interoperability (Health
Information Technology Standards), 4th ed -
http://www.springer.com/978-3-030-56882-5

**Pull request merged**
